"""
common_passwords.py
-------------------
Top 1000+ most commonly used passwords worldwide.
Sources: NordPass annual reports, Have I Been Pwned,
         SecLists, RockYou breach analysis, Wikipedia.

Used by the analyser to instantly flag weak passwords.
"""

from __future__ import annotations
from typing import Optional, Set


# Top 1000+ most common passwords in the world
COMMON_PASSWORDS: Set[str] = {
    # Rank 1-50 (Most used globally)
    "123456",
    "password",
    "123456789",
    "12345678",
    "12345",
    "1234567",
    "1234567890",
    "qwerty",
    "abc123",
    "111111",
    "password1",
    "iloveyou",
    "1q2w3e4r",
    "000000",
    "qwerty123",
    "zaq12wsx",
    "dragon",
    "sunshine",
    "princess",
    "letmein",
    "654321",
    "monkey",
    "27653",
    "1qaz2wsx",
    "123321",
    "qwertyuiop",
    "superman",
    "asdfghjkl",
    "football",
    "master",
    "welcome",
    "shadow",
    "123123",
    "michael",
    "login",
    "batman",
    "trustno1",
    "hello",
    "charlie",
    "donald",
    "admin",
    "qwerty1",
    "passw0rd",
    "whatever",
    "121212",
    "access",
    "696969",
    "jesus",
    "love",
    "soccer",
    # Rank 51-150
    "baseball",
    "shadow1",
    "master1",
    "killer",
    "jordan",
    "jennifer",
    "robert",
    "hunter",
    "thomas",
    "ranger",
    "buster",
    "daniel",
    "starwars",
    "andrea",
    "joshua",
    "jessica",
    "pepper",
    "george",
    "harley",
    "chester",
    "andrew",
    "charlie1",
    "samantha",
    "computer",
    "freedom",
    "ginger",
    "matthew",
    "austin",
    "maggie",
    "summer",
    "ashley",
    "nicole",
    "amanda",
    "justin",
    "cookie",
    "flower",
    "silver",
    "richard",
    "sparky",
    "diamond",
    "yellow",
    "bigdog",
    "taylor",
    "hannah",
    "sophie",
    "oliver",
    "abcdef",
    "secret",
    "sexy",
    "angel",
    "anthony",
    "tigger",
    "william",
    "michelle",
    "jackson",
    "purple",
    "chicken",
    "peanut",
    "thunder",
    "jasmine",
    "zxcvbnm",
    "merlin",
    "tucker",
    "bailey",
    "banana",
    "midnight",
    "golfer",
    "corvette",
    "yankees",
    "ferrari",
    "cheese",
    "dakota",
    "raiders",
    "cowboys",
    "falcon",
    "maverick",
    "matrix",
    "iceman",
    "guitar",
    "hammer",
    "gopher",
    "eagles",
    "winner",
    "phoenix",
    "mustang",
    "panther",
    "viking",
    "rocket",
    "warrior",
    "steelers",
    "packers",
    "tigers",
    "cardinal",
    "broncos",
    "dolphins",
    "blazer",
    "scorpion",
    "bulldog",
    "knight",
    # Rank 151-300
    "compaq",
    "paradise",
    "casper",
    "fishing",
    "mercedes",
    "pumpkin",
    "turtle",
    "porsche",
    "snowball",
    "genesis",
    "camaro",
    "fluffy",
    "phantom",
    "gandalf",
    "tiffany",
    "crystal",
    "colorado",
    "creative",
    "electric",
    "fantasy",
    "marlboro",
    "internet",
    "victoria",
    "champion",
    "december",
    "november",
    "remember",
    "platinum",
    "franklin",
    "scorpio",
    "mountain",
    "grizzly",
    "samurai",
    "raiders1",
    "hardcore",
    "rosebud",
    "redwings",
    "holiday",
    "anderson",
    "gateway",
    "captain",
    "monster",
    "bedroom",
    "peaches",
    "newyork",
    "jamaica",
    "college",
    "brother",
    "america",
    "alex",
    "apples",
    "biteme",
    "pantera",
    "trinity",
    "benjamin",
    "elizabeth",
    "swimming",
    "caroline",
    "cardinal1",
    "sabrina",
    "midnight1",
    "genesis1",
    "einstein",
    "nirvana",
    "freddy",
    "maxwell",
    "scooter",
    "indiana",
    "explorer",
    "ireland",
    "spencer",
    "matrix1",
    "stargate",
    "beatrice",
    "florida",
    "bollywood",
    "samsung",
    "nothing",
    "chicago",
    "friends",
    "butterfly",
    "elephant",
    "dolphins1",
    "mountain1",
    # Repeated character patterns
    "aaaaaa",
    "bbbbbb",
    "cccccc",
    "dddddd",
    "eeeeee",
    "ffffff",
    "gggggg",
    "hhhhhh",
    "iiiiii",
    "jjjjjj",
    "kkkkkk",
    "llllll",
    "mmmmmm",
    "nnnnnn",
    "oooooo",
    "pppppp",
    "qqqqqq",
    "rrrrrr",
    "ssssss",
    "tttttt",
    "uuuuuu",
    "vvvvvv",
    "wwwwww",
    "xxxxxx",
    "yyyyyy",
    "zzzzzz",
    # Number patterns
    "102030",
    "112233",
    "123654",
    "159753",
    "147258",
    "258456",
    "321654",
    "456789",
    "789456",
    "987654",
    "987654321",
    "999999",
    "888888",
    "777777",
    "666666",
    "555555",
    "444444",
    "333333",
    "222222",
    "010101",
    "020202",
    "101010",
    "110011",
    "112211",
    "131313",
    "141414",
    "151515",
    "161616",
    "171717",
    "181818",
    "191919",
    "202020",
    "212121",
    "232323",
    "242424",
    "252525",
    "262626",
    "272727",
    "282828",
    "292929",
    "313131",
    "343434",
    "353535",
    "363636",
    "373737",
    "383838",
    "393939",
    "414141",
    "424242",
    "434343",
    "454545",
    "464646",
    "474747",
    "484848",
    "494949",
    "505050",
    "515151",
    "525252",
    "535353",
    "545454",
    "565656",
    "575757",
    "585858",
    "595959",
    "606060",
    "616161",
    "626262",
    "636363",
    "646464",
    "656565",
    "676767",
    "686868",
    "707070",
    "717171",
    "727272",
    "737373",
    "747474",
    "757575",
    "767676",
    "787878",
    "797979",
    "808080",
    "818181",
    "828282",
    "838383",
    "848484",
    "858585",
    "868686",
    "878787",
    "898989",
    "909090",
    "919191",
    "929292",
    "939393",
    "949494",
    "959595",
    "969696",
    "979797",
    "989898",
    # Keyboard patterns
    "1q2w3e",
    "1q2w3e4r5t",
    "1qaz2wsx3edc",
    "q1w2e3r4",
    "q1w2e3r4t5",
    "qazwsx",
    "qazwsxedc",
    "qweasdzxc",
    "zaq1xsw2",
    "asdf1234",
    "asdfasdf",
    "asdfqwer",
    "zxcvzxcv",
    "1234qwer",
    "qwer1234",
    "poiuytrewq",
    "lkjhgfdsa",
    "mnbvcxz",
    "qpalzm",
    "plokij",
    "zaqwsx",
    "wsxedc",
    "edcrfv",
    "rfvtgb",
    "tgbyhn",
    "yhnujm",
    "asdfjkl",
    # Common words and phrases
    "password123",
    "password12",
    "password1234",
    "pass1234",
    "pass123",
    "passpass",
    "p@ssw0rd",
    "p@ss1234",
    "pa$$w0rd",
    "p@$$w0rd",
    "welcome1",
    "welcome123",
    "admin123",
    "admin1234",
    "administrator",
    "root",
    "root123",
    "toor",
    "test",
    "test123",
    "test1234",
    "guest",
    "guest123",
    "default",
    "changeme",
    "letmein1",
    "letmein123",
    "opensesame",
    "fuckyou",
    "fuck",
    "shit",
    "asshole",
    "fuckoff",
    "fuckyou1",
    "iloveu",
    "iloveyou1",
    "iloveyou2",
    "loveme",
    "lovely",
    "lover",
    "loveyou",
    "mylove",
    "mydarling",
    "sweetheart",
    "honeybee",
    "babe",
    "baby",
    "babygirl",
    "babyboy",
    "angel1",
    "angels",
    "beautiful",
    "handsome",
    "princess1",
    "prince",
    "king",
    "queen",
    "kingdom",
    "superstar",
    # Sports
    "basketball",
    "baseball1",
    "football1",
    "soccer1",
    "hockey",
    "tennis",
    "cricket",
    "arsenal",
    "chelsea",
    "liverpool",
    "manchester",
    "barcelona",
    "juventus",
    "realmadrid",
    "lakers",
    "jordan23",
    "lebron",
    "messi",
    "ronaldo",
    "neymar",
    "beckham",
    # Pop culture / Movies / Games
    "starwars1",
    "pokemon",
    "pikachu",
    "minecraft",
    "fortnite",
    "roblox",
    "callofduty",
    "halo",
    "zelda",
    "mario",
    "luigi",
    "naruto",
    "onepiece",
    "dragonball",
    "spiderman",
    "ironman",
    "avengers",
    "thanos",
    "joker",
    "harleyquinn",
    "batman1",
    "superman1",
    "wonderwoman",
    "hogwarts",
    "dumbledore",
    "voldemort",
    "hermione",
    "potter",
    "gandalf1",
    "frodo",
    "sauron",
    "terminator",
    "james007",
    "bond007",
    # Technology
    "google",
    "apple",
    "microsoft",
    "facebook",
    "twitter",
    "instagram",
    "youtube",
    "tiktok",
    "snapchat",
    "linkedin",
    "github",
    "amazon",
    "netflix",
    "spotify",
    "windows",
    "linux",
    "android",
    "iphone",
    # Common names
    "james",
    "john",
    "david",
    "chris",
    "mike",
    "jason",
    "ryan",
    "kevin",
    "brian",
    "steve",
    "mark",
    "scott",
    "eric",
    "jeffrey",
    "timothy",
    "larry",
    "randy",
    "frank",
    "patrick",
    "dennis",
    "maria",
    "sarah",
    "laura",
    "emily",
    "emma",
    "rachel",
    "megan",
    "karen",
    "nancy",
    "betty",
    "lisa",
    "sandra",
    "donna",
    "carol",
    "ruth",
    "sharon",
    "helen",
    "deborah",
    "stephanie",
    "katherine",
    "christina",
    "virginia",
    "catherine",
    "danielle",
    "natalie",
    "brittany",
    "heather",
    "teresa",
    "diana",
    "julie",
    "olivia",
    "alexander",
    "benjamin1",
    "nicholas",
    "jonathan",
    "christopher",
    "sebastian",
    # Animals
    "dolphin",
    "tiger",
    "dragon1",
    "wolf",
    "eagle",
    "bear",
    "lion",
    "snake",
    "shark",
    "spider",
    "rabbit",
    "kitten",
    "puppy",
    "doggy",
    "kitty",
    "panda",
    "unicorn",
    # Colors
    "red123",
    "blue123",
    "green123",
    "orange",
    "black",
    "white",
    "golden",
    "silver1",
    # Months and Days
    "january",
    "february",
    "march",
    "april",
    "may",
    "june",
    "july",
    "august",
    "september",
    "october",
    "january1",
    "monday",
    "tuesday",
    "wednesday",
    "thursday",
    "friday",
    "saturday",
    "sunday",
    # Countries and Cities
    "london",
    "paris",
    "tokyo",
    "berlin",
    "moscow",
    "sydney",
    "mumbai",
    "dubai",
    "canada",
    "brazil",
    "mexico",
    "india",
    "china",
    "japan",
    "russia",
    "germany",
    "france",
    "spain",
    "italy",
    "australia",
    # Food and Drinks
    "coffee",
    "chocolate",
    "vanilla",
    "strawberry",
    "mango",
    "burger",
    "tacos",
    "sushi",
    "pasta",
    "noodles",
    "beer",
    "vodka",
    "whiskey",
    "wine",
    "tequila",
    # Music
    "music",
    "guitar1",
    "piano",
    "drums",
    "metallica",
    "acdc",
    "nirvana1",
    "eminem",
    "drake",
    "beyonce",
    "rihanna",
    "shakira",
    "madonna",
    "beatles",
    "elvis",
    "jackson5",
    "coldplay",
    "linkinpark",
    "greenday",
    "blink182",
    # Common with year suffixes
    "password2024",
    "password2023",
    "password2022",
    "password2021",
    "password2020",
    "password2019",
    "qwerty2024",
    "qwerty2023",
    "admin2024",
    "admin2023",
    "welcome2024",
    "hello2024",
    "abc1234",
    "abcd1234",
    "abcde12345",
    # Special patterns
    "!@#$%^&*",
    "!@#$%",
    "a1b2c3d4",
    "1a2b3c4d",
    "aabb1122",
    "aa1234",
    "zz1234",
    "xx1234",
    "abc321",
    "xyz123",
    "xyz789",
    "aa123456",
    "aaaa1111",
    "abab1212",
    # Very short common
    "pass",
    "1234",
    "4321",
    "0000",
    "9999",
    "1111",
    "2222",
    "3333",
    "4444",
    "5555",
    "6666",
    "7777",
    "8888",
    "qwer",
    "asdf",
    "zxcv",
    "user",
    "temp",
    "demo",
    # Recent trending (2023-2024)
    "chatgpt",
    "openai",
    "crypto",
    "bitcoin",
    "ethereum",
    "blockchain",
    "nft12345",
    "metaverse",
    "tesla",
    "spacex",
    "elonmusk",
    "twitter123",
    "threads",
    "ai123456",
}


def _build_extended_set() -> Set[str]:
    """
    Expand COMMON_PASSWORDS with obvious mutations:
    UPPER, Title, lower, append digit 0-9, append ! or @, reverse.
    This catches people who think PASSWORD or Password1 is safe.
    """
    extended = set(COMMON_PASSWORDS)
    for pw in list(COMMON_PASSWORDS):
        extended.add(pw.lower())
        extended.add(pw.upper())
        extended.add(pw.title())
        extended.add(pw.capitalize())
        # Single digit suffix
        for d in range(10):
            extended.add(f"{pw}{d}")
            extended.add(f"{pw.title()}{d}")
        # Common symbol suffix
        for sym in ("!", "@", "#", "$", "!!", "123"):
            extended.add(f"{pw}{sym}")
            extended.add(f"{pw.title()}{sym}")
        # Reverse
        extended.add(pw[::-1])
    return extended


EXTENDED_COMMON_PASSWORDS: Set[str] = _build_extended_set()


def is_common_password(password: str) -> bool:
    """Check if password matches any known common password or mutation."""
    return password.lower() in {p.lower() for p in EXTENDED_COMMON_PASSWORDS}


def get_common_match(password: str) -> Optional[str]:
    """
    If the password matches a common password, return which base
    password it matched. Returns None if no match found.
    """
    low = password.lower()

    # Direct match
    for pw in COMMON_PASSWORDS:
        if low == pw.lower():
            return pw

    # Match with stripped trailing digits and symbols
    stripped = low.rstrip("0123456789!@#$%^&*")
    if stripped:
        for pw in COMMON_PASSWORDS:
            if stripped == pw.lower():
                return pw

    # Reverse match
    rev = low[::-1]
    for pw in COMMON_PASSWORDS:
        if rev == pw.lower():
            return f"{pw} (reversed)"

    return None


def get_password_rank(password: str) -> Optional[int]:
    """
    Return approximate rank if password is in top common list.
    Returns None if not found.
    """
    low = password.lower()
    sorted_common = sorted(COMMON_PASSWORDS)
    for i, pw in enumerate(sorted_common, 1):
        if low == pw.lower():
            return i
    return None


def get_total_count() -> int:
    """Return total number of passwords in the common database."""
    return len(COMMON_PASSWORDS)


def get_extended_count() -> int:
    """Return total number including mutations."""
    return len(EXTENDED_COMMON_PASSWORDS)
